/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import static spark.Spark.*;
import spark.Spark;
import spark.utils.IOUtils;
import spark.Request;
import java.util.Map;
import java.util.HashMap;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
		staticFileLocation("/public");
		
        get("/", (req, res) -> IOUtils.toString(Spark.class.getResourceAsStream("public/index.html")));
    }
}
